apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: nginx
  namespace: nginx3
spec:
  provider: kubernetes
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  service:
    port: 80
  analysis:
    interval: 1m
    threshold: 5
    maxWeight: 50
    stepWeight: 10
    metrics:
      - name: request-success-rate
        threshold: 99
        interval: 30s
      - name: request-duration
        threshold: 500
        interval: 30s
