# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx
# spec:
#   type: LoadBalancer
#   ports:
#   - port: 80
#     targetPort: 80
#   selector:
#     app: nginx

apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx2

spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080  
  selector:
    app: nginx
